### ISSUE TITLE
Change export path to root directory of app and test projects

### ISSUE THREAD

**Issue by OtterWhisperer** [365businessdev/vscode-alxmldocumentation#62] opened 2021-05-26 13:13 UTC
Dear 365businessdev developers,

in regards to https://github.com/365businessdev/vscode-alxmldocumentation/issues/18#issuecomment-663552820 I'm curious: how is it possible to configure the "al-xml-doc.DocumentationExportPath in a way that the parent folder would be set. I tried a bunch of other vs code extension whom give me the parent directory resulting in a "path.replace" error. The ${workspaceFolder} doesn't fit my needs.

As a developer I want to be able to export the AL documentation (which by the way imo is an awesome VS Code Extension!) for the App and for the Test packages to my parent folder. Idealy this process can be triggered when building the extension (CTRL+SHFIT+B and so on).

Thank you very much in advance

**Comment by sirhc101** [comment] 2021-05-31 14:18
Thank you for reporting. This looks like a bug. I will fix this as soon as possible

**Comment by sirhc101** [comment] 2021-06-18 17:36
Sorry for waiting. I've fixed the issue and shipped the version 1.1.3 in marketplace. It should update automatically.
From now you are able to use relative paths or `${workspaceFolder}` if you want to place your documentation in the workspace root.

**Comment by OtterWhisperer** [comment] 2021-06-18 22:13
Nah, I'm good, thank you so much! That was faster then I expected and my excitment tonight was skyrocking as iI saw the update of this issue. Unfortunately the bad news is that the `${workspaceFolder}` doesn't work for my system.

In the error message it says:
> EINVAL: invalid argument, mkdir 'file:///d%3A/OtterWhisperer/github/d365bc-al-template/docs'

The `D:\OtterWhisperer\github\d365bc-al-template` folder exists and is the workspaceFolder: `"al-xml-doc.DocumentationExportPath": "${workspaceFolder}/docs",`.

My current vs code specs (as you can also see I'm running win10):
![image](https://user-images.githubusercontent.com/25108568/122619741-6cda1900-d091-11eb-9214-19039009d640.png)

**Comment by OtterWhisperer** [comment] 2021-06-19 08:06
I tried to come up with a solution for this and what does the trick for me was this change: https://github.com/OtterWhisperer/vscode-alxmldocumentation/commit/9f6e82e1e8d0199979b304b7b604b4ba3501db48. Would love to hear your opinion on this. Have a nice weekend!

**Comment by sirhc101** [comment] 2021-06-19 12:36
Oh you're right. It worked for me in one project, but in another I got the same issue.
I'm able to reproduce it.

**Comment by sirhc101** [comment] 2021-06-19 12:39
@OtterWhisperer You're fix looks good to me. I will merge this and release a fixed version after some testing in different scenarios.

Thank you very much

**Comment by sirhc101** [comment] 2021-06-20 14:31
Thank you very much for contribution @OtterWhisperer 
I merged your contribution from [OtterWhisperer@9f6e82e](https://github.com/OtterWhisperer/vscode-alxmldocumentation/commit/9f6e82e1e8d0199979b304b7b604b4ba3501db48).

New version 1.1.4 is alredy shipped to marketplace

**Closed by sirhc101** 2021-06-20 14:31 UTC
Labels: bug, released
